version: '3'
services:
  www:
    build:
      context: ./docker/www
      dockerfile: Dockerfile
    container_name: extractor-www
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    restart: always